export let database1 = [
  {
    name: "koran",
    img: "./img/koran.png",
    text: "jwbvwbvwlknlkwn",
    id: 1,
  },
  {
    name: "arafat",
    img: "./img/arafat.png",
    text: "jwbvwbvwlknlkwn",
    id: 2,
  },
  {
    name: "mesqid_1",
    img: "./img/mesqid_1.png",
    text: "jwbvwbvwlknlkwn",
    id: 3,
  },
  {
    name: "mesqid_2",
    img: "./img/mesqid_2.png",
    text: "jwbvwbvwlknlkwn",
    id: 4,
  },
  {
    name: "tower",
    img: "./img/tower.png",
    text: "jwbvwbvwlknlkwn",
    id: 5,
  },
  {
    name: "mesqid_3",
    img: "./img/mesqid_3.png",
    text: "jwbvwbvwlknlkwn",
    id: 6,
  },
  {
    name: "mesqid_4",
    img: "./img/mesqid_4.png",
    text: "jwbvwbvwlknlkwn",
    id: 7,
  },
  {
    name: "mesqid_5",
    img: "./img/mesqid_5.png",
    text: "jwbvwbvwlknlkwn",
    id: 8,
  },
  {
    name: "mesqid_6",
    img: "./img/mesqid_6.png",
    text: "jwbvwbvwlknlkwn",
    id: 9,
  },

  {
    name: "mesqid_7",
    img: "./img/mesqid_7.png",
    text: "jwbvwbvwlknlkwn",
    id: 10,
  },
  {
    name: "mesqid_8",
    img: "./img/mesqid_8.png",
    text: "jwbvwbvwlknlkwn",
    id: 11,
  },
  {
    name: "mesqid_9",
    img: "./img/mesqid_9.png",
    text: "jwbvwbvwlknlkwn",
    id: 12,
  },
  {
    name: "kibla",
    img: "./img/kibla.png",
    text: "jwbvwbvwlknlkwn",
    id: 13,
  },
  {
    name: "mesqid_10",
    img: "./img/mesqid_10.png",
    text: "jwbvwbvwlknlkwn",
    id: 14,
  },
  {
    name: "mesqid_11",
    img: "./img/mesqid_11.png",
    text: "jwbvwbvwlknlkwn",
    id: 15,
  },
  {
    name: "mesqid_12",
    img: "./img/mesqid_12.png",
    text: "jwbvwbvwlknlkwn",
    id: 16,
  },
  {
    name: "mesqid_13",
    img: "./img/mesqid_13.png",
    text: "jwbvwbvwlknlkwn",
    id: 17,
  },
  
  {
    name: "mesqid_14",
    img: "./img/mesqid_14.png",
    text: "jwbvwbvwlknlkwn",
    id: 18,
  },
  {
    name: "mesqid_15",
    img: "./img/mesqid_15.png",
    text: "jwbvwbvwlknlkwn",
    id: 19,
  },
  {
    name: "mesqid_16",
    img: "./img/mesqid_16.png",
    text: "jwbvwbvwlknlkwn",
    id: 20,
  },
  {
    name: "mesqid_17",
    img: "./img/mesqid_17.png",
    text: "jwbvwbvwlknlkwn",
    id: 21,
  },
  {
    name: "mesqid_18",
    img: "./img/mesqid_18.png",
    text: "jwbvwbvwlknlkwn",
    id: 22,
  },
  {
    name: "mesqid_19",
    img: "./img/mesqid_19.png",
    text: "jwbvwbvwlknlkwn",
    id: 23,
  },
  {
    name: "mesqid_20",
    img: "./img/mesqid_20.png",
    text: "jwbvwbvwlknlkwn",
    id: 24,
  },
  {
    name: "mesqid_21",
    img: "./img/mesqid_21.png",
    text: "jwbvwbvwlknlkwn",
    id: 25,
  },
  {
    name: "mesqid_22",
    img: "./img/mesqid_22.png",
    text: "jwbvwbvwlknlkwn",
    id: 26,
  },
  {
    name: "mesqid_23",
    img: "./img/mesqid_23.png",
    text: "jwbvwbvwlknlkwn",
    id: 27,
  },
  {
    name: "mesqid_24",
    img: "./img/mesqid_24.png",
    text: "jwbvwbvwlknlkwn",
    id: 28,
  },
  {
    name: "mesqid_25",
    img: "./img/mesqid_25.png",
    text: "jwbvwbvwlknlkwn",
    id: 29,
  },
  {
    name: "mesqid_26",
    img: "./img/mesqid_26.png",
    text: "jwbvwbvwlknlkwn",
    id: 30,
  }
];
